### ISSUE TITLE
ux: cannot add vuln

### ISSUE THREAD

**Issue by bodik** [snerstack/sner-monorepo#62]
storage > service > +V > fill form > save >> cannot add vuln

```
werkzeug 127.0.0.1 - - [06/May/2024 10:15:06] "POST /backend/storage/vuln/add/service/53238 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/sner/server/venv/lib/python3.11/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/sner/server/venv/lib/python3.11/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/sner/server/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/sner/server/venv/lib/python3.11/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/sner/server/venv/lib/python3.11/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/sner/server/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/sner/server/venv/lib/python3.11/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/sner/server/venv/lib/python3.11/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/sner/server/bin/../sner/server/auth/core.py", line 70, in decorated_view
    return fnc(*args, **kwargs)
  File "/opt/sner/server/bin/../sner/server/storage/views/vuln.py", line 105, in vuln_add_route
    host, service = get_related_models(model_name, model_id)
  File "/opt/sner/server/bin/../sner/server/storage/core.py", line 34, in get_related_models
    host = service.host
AttributeError: 'NoneType' object has no attribute 'host'
```

**Comment by bodik** [comment]
fixed in current workbranch
